.DEFAULT_GOAL := help

GSH        := $(CURDIR)/.gerbil/bin/gsh
OILS_DIR   := _vendor/oils
SH_SPEC    := python3 $(CURDIR)/test/run_spec.py
BASH       := /bin/bash

export GERBIL_BUILD_CORES := $(shell echo $$(( $$(nproc) / 2 )))

# Build tier: tiny (default), small, medium, large
GSH_TIER ?= tiny

# Static binary build variables
ARCH := $(shell uname -m)
PWD := $(shell pwd)
DOCKER_IMAGE := "gerbil/gerbil:$(ARCH)-master"
UID := $(shell id -u)
GID := $(shell id -g)

# --- Gambitgsc (embedded compiler) ---

GAMBITGSC_DIR := _vendor/gambitgsc
RUNTIME_DIR := _vendor/gerbil-runtime
DLOPEN_DIR := _vendor/gsh-dlopen

gambitgsc:
	$(CURDIR)/scripts/generate-gambitgsc

gerbil-runtime:
	$(CURDIR)/scripts/generate-gerbil-runtime

gsh-dlopen:
	cc -O2 -c $(DLOPEN_DIR)/gsh-dlopen.c -o $(DLOPEN_DIR)/gsh-dlopen.o

# --- Stage file generation ---
# Generate stage.ss based on GSH_TIER before building.
# stage.ss imports tier-specific modules (compiler, coreutils) that
# self-register at module init time.

define STAGE_TINY
;;; stage.ss — Build tier configuration (generated by Makefile)
;;; DO NOT EDIT — this file is overwritten by `make build` based on GSH_TIER.
;;; Tier: tiny — core shell only, no eval/compiler/coreutils
(export #t)
(import :gsh/registry)
(*gsh-tier* "tiny")
endef

define STAGE_SMALL
;;; stage.ss — Build tier configuration (generated by Makefile)
;;; DO NOT EDIT — this file is overwritten by `make build` based on GSH_TIER.
;;; Tier: small — core shell + Gerbil eval
(export #t)
(import :gsh/registry
        :gerbil/expander)
(*gsh-tier* "small")
endef

define STAGE_MEDIUM
;;; stage.ss — Build tier configuration (generated by Makefile)
;;; DO NOT EDIT — this file is overwritten by `make build` based on GSH_TIER.
;;; Tier: medium — core shell + Gerbil eval + compiler (,use foo.ss)
(export #t)
(import :gsh/registry
        :gsh/compiler)
(*gsh-tier* "medium")
endef

define STAGE_LARGE
;;; stage.ss — Build tier configuration (generated by Makefile)
;;; DO NOT EDIT — this file is overwritten by `make build` based on GSH_TIER.
;;; Tier: large — core shell + Gerbil eval + compiler + coreutils
(export #t)
(import :gsh/registry
        :gsh/compiler
        :gsh/coreutils)
(*gsh-tier* "large")
endef

export STAGE_TINY STAGE_SMALL STAGE_MEDIUM STAGE_LARGE

generate-stage:
	@case "$(GSH_TIER)" in \
	  tiny)   echo "$$STAGE_TINY"   > stage.ss ;; \
	  small)  echo "$$STAGE_SMALL"  > stage.ss ;; \
	  medium) echo "$$STAGE_MEDIUM" > stage.ss ;; \
	  large)  echo "$$STAGE_LARGE"  > stage.ss ;; \
	  *)      echo "Unknown GSH_TIER: $(GSH_TIER)"; exit 1 ;; \
	esac
	@echo "Generated stage.ss for tier: $(GSH_TIER)"

# --- Build prerequisites per tier ---
# tiny/small: no gambitgsc needed
# medium/large: need gambitgsc for compile-file

TIER_PREREQS :=
ifneq (,$(filter medium large,$(GSH_TIER)))
  TIER_PREREQS += gambitgsc
endif

# GERBIL_GSC: use wrapper for medium/large tiers (injects gambitgsc compiler modules)
ifneq (,$(filter medium large,$(GSH_TIER)))
  BUILD_GSC := $(CURDIR)/scripts/gsc-with-gambitgsc
endif

# GERBIL_LOADPATH: only include coreutils for large tier
ifeq ($(GSH_TIER),large)
  BUILD_LOADPATH := $$HOME/.gerbil/lib:$$HOME/.gerbil/pkg/gerbil-pcre/.gerbil/lib:$$HOME/.gerbil/pkg/github.com/ober/gerbil-coreutils/.gerbil/lib:$$GERBIL_LOADPATH
else
  BUILD_LOADPATH := $$HOME/.gerbil/lib:$$GERBIL_LOADPATH
endif

# --- Build ---

build: generate-stage $(TIER_PREREQS)
	GSH_TIER=$(GSH_TIER) \
	$(if $(BUILD_GSC),GERBIL_GSC=$(BUILD_GSC)) \
	GERBIL_LOADPATH="$(BUILD_LOADPATH)" \
	LIBRARY_PATH="$$(brew --prefix openssl@3 2>/dev/null)/lib:$$LIBRARY_PATH" \
	gerbil build
	@# Patch rpath for brew openssl (needed by coreutils crypto: cksum, md5sum, sha*sum)
	@if [ "$(GSH_TIER)" = "large" ]; then \
	  OPENSSL_LIB="$$(brew --prefix openssl@3 2>/dev/null)/lib"; \
	  if [ -n "$$OPENSSL_LIB" ] && [ -d "$$OPENSSL_LIB" ] && command -v patchelf >/dev/null 2>&1; then \
	    patchelf --set-rpath "$$OPENSSL_LIB" $(GSH) 2>/dev/null || true; \
	  fi; \
	fi

# Convenience targets for each tier
build-tiny:
	$(MAKE) build GSH_TIER=tiny

build-small:
	$(MAKE) build GSH_TIER=small

build-medium:
	$(MAKE) build GSH_TIER=medium

build-large:
	$(MAKE) build GSH_TIER=large

# --- Library build ---
# Compile all core modules as a library (no executable).
# Other Gerbil projects can then: (import :gsh/lib)

lib:
	GSH_LIB_ONLY=1 GERBIL_LOADPATH="$$HOME/.gerbil/lib:$$GERBIL_LOADPATH" gerbil build

install-lib: lib
	@echo "Installing gsh library via gxpkg link..."
	@cd $(HOME) && gxpkg link gsh $(CURDIR) || true
	@cd $(HOME) && gxpkg build gsh
	@echo "Installed. Other projects can now: (import :gsh/lib)"

uninstall-lib:
	@cd $(HOME) && gxpkg unlink gsh || true
	@echo "Unlinked gsh library"

install:
	@if [ -f static/gsh ]; then \
	  SRC=static/gsh; \
	elif [ -f $(GSH) ]; then \
	  SRC=$(GSH); \
	else \
	  $(MAKE) build; \
	  SRC=$(GSH); \
	fi; \
	echo "Cleaning old gsh artifacts from ~/.gerbil/ and ~/.local/bin/..."; \
	rm -f ~/.gerbil/bin/gsh; \
	rm -f ~/.local/bin/gsh; \
	rm -rf ~/.gerbil/lib/gsh/; \
	rm -f ~/.gerbil/lib/static/gsh__*.scm; \
	echo "Installing $$SRC..."; \
	mkdir -p ~/.local/bin; \
	cp "$$SRC" ~/.local/bin/gsh; \
	chmod +x ~/.local/bin/gsh; \
	echo "Installed gsh to ~/.local/bin/gsh"

# --- Spec test targets ---

# Compat tests require the large tier (coreutils for ls, etc.)
compat-build:
	$(MAKE) build GSH_TIER=large

# Run the smoke test (quick sanity check)
compat-smoke: compat-build $(OILS_DIR)
	$(SH_SPEC) $(OILS_DIR)/spec/smoke.test.sh $(BASH) $(GSH)

# Run all Tier 0 spec tests
compat-tier0: compat-build $(OILS_DIR)
	@for f in smoke pipeline redirect redirect-multi \
	          builtin-eval-source command-sub comments exit-status; do \
	  echo "=== $$f ==="; \
	  $(SH_SPEC) $(OILS_DIR)/spec/$$f.test.sh $(BASH) $(GSH) || true; \
	  echo; \
	done

# Run all Tier 1 spec tests
compat-tier1: compat-build $(OILS_DIR)
	@for f in here-doc quote word-eval word-split var-sub var-sub-quote \
	          var-num var-op-test var-op-strip var-op-len assign tilde; do \
	  echo "=== $$f ==="; \
	  $(SH_SPEC) $(OILS_DIR)/spec/$$f.test.sh $(BASH) $(GSH) || true; \
	  echo; \
	done

# Run all Tier 2 spec tests
compat-tier2: compat-build $(OILS_DIR)
	@for f in arith glob brace-expansion case_ if_ loop for-expr subshell \
	          sh-func builtin-echo builtin-printf builtin-read builtin-cd \
	          builtin-set builtin-type builtin-trap builtin-bracket \
	          builtin-misc builtin-process background command-parsing \
	          var-op-bash var-op-slice assign-extended; do \
	  echo "=== $$f ==="; \
	  $(SH_SPEC) $(OILS_DIR)/spec/$$f.test.sh $(BASH) $(GSH) || true; \
	  echo; \
	done

# Run a single spec file: make compat-one SPEC=smoke
compat-one: compat-build $(OILS_DIR)
	$(SH_SPEC) $(OILS_DIR)/spec/$(SPEC).test.sh $(BASH) $(GSH)

# Run a specific test range: make compat-range SPEC=smoke RANGE=3-5
compat-range: compat-build $(OILS_DIR)
	$(SH_SPEC) --range $(RANGE) $(OILS_DIR)/spec/$(SPEC).test.sh $(BASH) $(GSH)

# Run all tiers combined and update the compatibility report
compat: compat-tier0 compat-tier1 compat-tier2
	@python3 $(CURDIR)/test/gen_compat_report.py --output $(CURDIR)/bash-compatibility.md \
	  $(OILS_DIR) $(BASH) $(GSH) 2>&1 | grep -v "^  Running"
	@echo "Updated bash-compatibility.md"

# Verbose single spec: make compat-debug SPEC=smoke
compat-debug: compat-build $(OILS_DIR)
	$(SH_SPEC) -v $(OILS_DIR)/spec/$(SPEC).test.sh $(BASH) $(GSH)

# --- Benchmarks ---

SHELLBENCH_DIR := $(HOME)/mine/shellbench

bench: install
	@if [ ! -d "$(SHELLBENCH_DIR)" ]; then \
	  echo "Error: shellbench not found at $(SHELLBENCH_DIR)"; \
	  exit 1; \
	fi
	@cd $(SHELLBENCH_DIR) && setsid ./shellbench -s $(HOME)/.gerbil/bin/gsh,bash sample/*

# --- Vendor management ---

$(OILS_DIR):
	git clone --depth 1 https://github.com/oils-for-unix/oils.git $(OILS_DIR)

vendor-update: $(OILS_DIR)
	cd $(OILS_DIR) && git pull --ff-only

clean:
	gerbil clean
	rm -rf .gerbil
	rm -f ~/.gerbil/bin/gsh
	rm -rf ~/.gerbil/lib/gsh/
	rm -f ~/.gerbil/lib/static/gsh__*.scm
	rm -f $(GAMBITGSC_DIR)/*.o $(GAMBITGSC_DIR)/*.c $(GAMBITGSC_DIR)/LINK_ORDER $(GAMBITGSC_DIR)/.gambit-version
	rm -f $(RUNTIME_DIR)/*.o $(RUNTIME_DIR)/*.scm $(RUNTIME_DIR)/*.c $(RUNTIME_DIR)/LINK_ORDER $(RUNTIME_DIR)/.gerbil-version
	rm -f $(DLOPEN_DIR)/*.o

# --- Static binary (Docker) ---

static: linux-static-docker

# Static tier: default large for full-featured static binary
GSH_STATIC_TIER ?= large

clean-docker:
	-rm -rf .gerbil 2>/dev/null || true
	docker run --rm -v $(PWD):/src:z alpine rm -rf /src/.gerbil

check-root:
	@if [ "${UID}" -eq 0 ]; then \
	  git config --global --add safe.directory /src; \
	fi

build-static: check-root gerbil-runtime gsh-dlopen
	$(MAKE) generate-stage GSH_TIER=$(GSH_STATIC_TIER)
	@# Install gambitgsc only for medium/large (embedded compiler)
	@case "$(GSH_STATIC_TIER)" in medium|large) $(MAKE) gambitgsc ;; esac
	@# Install coreutils only for large tier
	@case "$(GSH_STATIC_TIER)" in large) \
	  gxpkg install github.com/ober/gerbil-pcre2; \
	  GERBIL_BUILD_CORES=1 gxpkg install github.com/ober/gerbil-coreutils ;; esac
	GSH_TIER=$(GSH_STATIC_TIER) GSH_STATIC=1 \
	$(if $(filter medium large,$(GSH_STATIC_TIER)),GERBIL_GSC=$(CURDIR)/scripts/gsc-with-gambitgsc) \
	GERBIL_LOADPATH="$$HOME/.gerbil/lib:$$(pwd)/.gerbil/lib:$$GERBIL_LOADPATH" \
	gerbil build

linux-static-docker: clean-docker
	docker run --rm \
	  --ulimit nofile=8192:8192 \
	  -v $(PWD):/src:z \
	  $(DOCKER_IMAGE) \
	  sh -c "apk add --no-cache pcre2-dev pcre2-static su-exec && \
	         chown -R $(UID):$(GID) /opt/ && \
	         mkdir -p /tmp/gsh-build && chown $(UID):$(GID) /tmp/gsh-build && \
	         exec su-exec $(UID):$(GID) env HOME=/tmp/gsh-build sh -c '\
	           cd /src && \
	           make build-static GSH_STATIC_TIER=$(GSH_STATIC_TIER) && \
	           mkdir -p static && \
	           cp .gerbil/bin/gsh static/gsh'"
	@# Clean Docker artifacts so local builds are never corrupted
	-rm -rf .gerbil 2>/dev/null || true
	docker run --rm -v $(PWD):/src:z alpine sh -c \
	  "rm -rf /src/.gerbil /src/$(GAMBITGSC_DIR)/*.o /src/$(GAMBITGSC_DIR)/*.c \
	   /src/$(GAMBITGSC_DIR)/LINK_ORDER /src/$(GAMBITGSC_DIR)/.gambit-version \
	   /src/$(RUNTIME_DIR)/*.o /src/$(RUNTIME_DIR)/*.scm /src/$(RUNTIME_DIR)/*.c \
	   /src/$(RUNTIME_DIR)/LINK_ORDER /src/$(RUNTIME_DIR)/.gerbil-version \
	   /src/$(DLOPEN_DIR)/*.o"
	@echo "Static binary: static/gsh"

# Static tier convenience targets
static-tiny:
	$(MAKE) static GSH_STATIC_TIER=tiny

static-small:
	$(MAKE) static GSH_STATIC_TIER=small

static-medium:
	$(MAKE) static GSH_STATIC_TIER=medium

static-large:
	$(MAKE) static GSH_STATIC_TIER=large

help:
	@echo "gsh — Gerbil Shell"
	@echo ""
	@echo "Build tiers (dynamic):        Binary size:"
	@echo "  make build                   tiny  (21MB) — shell only"
	@echo "  make build-small             small (23MB) — + ,eval"
	@echo "  make build-medium            medium(37MB) — + ,use foo.ss"
	@echo "  make build-large             large (42MB) — + 101 coreutils"
	@echo ""
	@echo "Build tiers (static, via Docker):"
	@echo "  make static-tiny"
	@echo "  make static-small"
	@echo "  make static-medium"
	@echo "  make static-large            (default for 'make static')"
	@echo ""
	@echo "Library (for embedding in other Gerbil projects):"
	@echo "  make lib                     Build library modules only"
	@echo "  make install-lib             Build + link via gxpkg"
	@echo "  make uninstall-lib           Unlink gxpkg"
	@echo ""
	@echo "Other:"
	@echo "  make install                 Install to ~/.local/bin/gsh"
	@echo "  make clean                   Remove build artifacts"
	@echo ""
	@echo "Compat tests (auto-builds large tier):"
	@echo "  make compat-smoke            Quick 18-test sanity check"
	@echo "  make compat-tier0            Tier 0 spec tests"
	@echo "  make compat-tier1            Tier 1 spec tests"
	@echo "  make compat-tier2            Tier 2 spec tests"
	@echo "  make compat                  All tiers + update report"
	@echo "  make compat-one SPEC=name    Single spec file"
	@echo "  make compat-range SPEC=name RANGE=3-5"
	@echo "  make compat-debug SPEC=name  Verbose single spec"
	@echo ""
	@echo "Benchmarks:"
	@echo "  make bench                   Run shellbench suite"

.PHONY: help build build-tiny build-small build-medium build-large \
        lib install-lib uninstall-lib \
        install clean generate-stage \
        compat compat-smoke compat-tier0 compat-tier1 compat-tier2 compat-build \
        compat-one compat-range compat-debug compat-report vendor-update bench \
        static static-tiny static-small static-medium static-large \
        clean-docker check-root build-static linux-static-docker \
        gambitgsc gerbil-runtime gsh-dlopen
