#ifdef ___LINKER_INFO
; File: "gerbil__tools__gxensemble__env.c", produced by Gambit v4.9.7
(
409007
(C)
"gerbil__tools__gxensemble__env"
("gerbil__tools__gxensemble__env")
()
(("gerbil__tools__gxensemble__env"))
( #|*/"*/"symbols|#
"add"
"domain"
"gerbil/tools/gxensemble/env#do-env-domain"
"gerbil/tools/gxensemble/env#do-env-known-servers"
"gerbil/tools/gxensemble/env#do-env-supervisor"
"gerbil__tools__gxensemble__env"
"gerbil__tools__gxensemble__env#"
"maybe"
"remove"
"server-addresses"
"server-id"
"set"
) #|*/"*/"symbols|#
( #|*/"*/"keywords|#
"create"
"path"
"truncate"
) #|*/"*/"keywords|#
( #|*/"*/"globals-s-d|#
"gerbil__tools__gxensemble__env#"
) #|*/"*/"globals-s-d|#
( #|*/"*/"globals-s-nd|#
"gerbil/tools/gxensemble/env#do-env-domain"
"gerbil/tools/gxensemble/env#do-env-known-servers"
"gerbil/tools/gxensemble/env#do-env-supervisor"
"gerbil/tools/gxensemble/env::timestamp"
) #|*/"*/"globals-s-nd|#
( #|*/"*/"globals-ns|#
"##append"
"##call-with-output-file"
"absent-value"
"displayln"
"error"
"filter"
"gerbil/tools/gxensemble/util#get-ensemble-domain"
"gerbil/tools/gxensemble/util#write-result"
"hash->list"
"hash-get"
"hash-put!"
"hash-ref__%"
"hash-remove!"
"make-hash-table__%"
"member"
"std/actor-v18/path#ensemble-domain-file-path__0"
"std/actor-v18/path#ensemble-domain-supervisor-path__0"
"std/actor-v18/path#ensemble-domain-supervisor__0"
"std/actor-v18/path#ensemble-known-servers-path__0"
"std/actor-v18/path#ensemble-known-servers__0"
"std/actor-v18/path#ensemble-server-unix-addr"
"std/iter#iter"
"std/iter#iter-end"
"write"
) #|*/"*/"globals-ns|#
( #|*/"*/"meta-info|#
) #|*/"*/"meta-info|#
)
#else
#define ___VERSION 409007
#define ___MODULE_NAME "gerbil__tools__gxensemble__env"
#define ___LINKER_ID ___LNK_gerbil____tools____gxensemble____env
#define ___MH_PROC ___H_gerbil____tools____gxensemble____env
#define ___SCRIPT_LINE 0
#define ___SYMCOUNT 12
#define ___KEYCOUNT 3
#define ___GLOCOUNT 29
#define ___SUPCOUNT 5
#define ___SUBCOUNT 8
#define ___LBLCOUNT 89
#define ___MODDESCR ___REF_SUB(5)
#include "gambit.h"

___NEED_SYM(___S_add)
___NEED_SYM(___S_domain)
___NEED_SYM(___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___NEED_SYM(___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___NEED_SYM(___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___NEED_SYM(___S_gerbil____tools____gxensemble____env)
___NEED_SYM(___S_gerbil____tools____gxensemble____env_23_)
___NEED_SYM(___S_maybe)
___NEED_SYM(___S_remove)
___NEED_SYM(___S_server_2d_addresses)
___NEED_SYM(___S_server_2d_id)
___NEED_SYM(___S_set)

___NEED_KEY(___K_create)
___NEED_KEY(___K_path)
___NEED_KEY(___K_truncate)

___NEED_GLO(___G__23__23_append)
___NEED_GLO(___G__23__23_call_2d_with_2d_output_2d_file)
___NEED_GLO(___G_absent_2d_value)
___NEED_GLO(___G_displayln)
___NEED_GLO(___G_error)
___NEED_GLO(___G_filter)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain)
___NEED_GLO(___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result)
___NEED_GLO(___G_gerbil____tools____gxensemble____env_23_)
___NEED_GLO(___G_hash_2d__3e_list)
___NEED_GLO(___G_hash_2d_get)
___NEED_GLO(___G_hash_2d_put_21_)
___NEED_GLO(___G_hash_2d_ref_____25_)
___NEED_GLO(___G_hash_2d_remove_21_)
___NEED_GLO(___G_make_2d_hash_2d_table_____25_)
___NEED_GLO(___G_member)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___NEED_GLO(___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr)
___NEED_GLO(___G_std_2f_iter_23_iter)
___NEED_GLO(___G_std_2f_iter_23_iter_2d_end)
___NEED_GLO(___G_write)

___BEGIN_SYM
___DEF_SYM(0,___S_add,"add")
___DEF_SYM(1,___S_domain,"domain")
___DEF_SYM(2,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,"gerbil/tools/gxensemble/env#do-env-domain")

___DEF_SYM(3,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,"gerbil/tools/gxensemble/env#do-env-known-servers")

___DEF_SYM(4,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,"gerbil/tools/gxensemble/env#do-env-supervisor")

___DEF_SYM(5,___S_gerbil____tools____gxensemble____env,"gerbil__tools__gxensemble__env")

___DEF_SYM(6,___S_gerbil____tools____gxensemble____env_23_,"gerbil__tools__gxensemble__env#")

___DEF_SYM(7,___S_maybe,"maybe")
___DEF_SYM(8,___S_remove,"remove")
___DEF_SYM(9,___S_server_2d_addresses,"server-addresses")
___DEF_SYM(10,___S_server_2d_id,"server-id")
___DEF_SYM(11,___S_set,"set")
___END_SYM

#define ___SYM_add ___SYM(0,___S_add)
#define ___SYM_domain ___SYM(1,___S_domain)
#define ___SYM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain ___SYM(2,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
#define ___SYM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers ___SYM(3,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
#define ___SYM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor ___SYM(4,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
#define ___SYM_gerbil____tools____gxensemble____env ___SYM(5,___S_gerbil____tools____gxensemble____env)
#define ___SYM_gerbil____tools____gxensemble____env_23_ ___SYM(6,___S_gerbil____tools____gxensemble____env_23_)
#define ___SYM_maybe ___SYM(7,___S_maybe)
#define ___SYM_remove ___SYM(8,___S_remove)
#define ___SYM_server_2d_addresses ___SYM(9,___S_server_2d_addresses)
#define ___SYM_server_2d_id ___SYM(10,___S_server_2d_id)
#define ___SYM_set ___SYM(11,___S_set)

___BEGIN_KEY
___DEF_KEY(0,___K_create,"create")
___DEF_KEY(1,___K_path,"path")
___DEF_KEY(2,___K_truncate,"truncate")
___END_KEY

#define ___KEY_create ___KEY(0,___K_create)
#define ___KEY_path ___KEY(1,___K_path)
#define ___KEY_truncate ___KEY(2,___K_truncate)

___BEGIN_GLO
___DEF_GLO(0,"gerbil/tools/gxensemble/env#do-env-domain")

___DEF_GLO(1,"gerbil/tools/gxensemble/env#do-env-known-servers")

___DEF_GLO(2,"gerbil/tools/gxensemble/env#do-env-supervisor")

___DEF_GLO(3,"gerbil/tools/gxensemble/env::timestamp")

___DEF_GLO(4,"gerbil__tools__gxensemble__env#")
___DEF_GLO(5,"##append")
___DEF_GLO(6,"##call-with-output-file")
___DEF_GLO(7,"absent-value")
___DEF_GLO(8,"displayln")
___DEF_GLO(9,"error")
___DEF_GLO(10,"filter")
___DEF_GLO(11,"gerbil/tools/gxensemble/util#get-ensemble-domain")

___DEF_GLO(12,"gerbil/tools/gxensemble/util#write-result")

___DEF_GLO(13,"hash->list")
___DEF_GLO(14,"hash-get")
___DEF_GLO(15,"hash-put!")
___DEF_GLO(16,"hash-ref__%")
___DEF_GLO(17,"hash-remove!")
___DEF_GLO(18,"make-hash-table__%")
___DEF_GLO(19,"member")
___DEF_GLO(20,"std/actor-v18/path#ensemble-domain-file-path__0")

___DEF_GLO(21,"std/actor-v18/path#ensemble-domain-supervisor-path__0")

___DEF_GLO(22,"std/actor-v18/path#ensemble-domain-supervisor__0")

___DEF_GLO(23,"std/actor-v18/path#ensemble-known-servers-path__0")

___DEF_GLO(24,"std/actor-v18/path#ensemble-known-servers__0")

___DEF_GLO(25,"std/actor-v18/path#ensemble-server-unix-addr")

___DEF_GLO(26,"std/iter#iter")
___DEF_GLO(27,"std/iter#iter-end")
___DEF_GLO(28,"write")
___END_GLO

#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain ___GLO(0,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain ___PRM(0,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers ___GLO(1,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers ___PRM(1,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor ___GLO(2,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor ___PRM(2,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp ___GLO(3,___G_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp ___PRM(3,___G_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp)
#define ___GLO_gerbil____tools____gxensemble____env_23_ ___GLO(4,___G_gerbil____tools____gxensemble____env_23_)
#define ___PRM_gerbil____tools____gxensemble____env_23_ ___PRM(4,___G_gerbil____tools____gxensemble____env_23_)
#define ___GLO__23__23_append ___GLO(5,___G__23__23_append)
#define ___PRM__23__23_append ___PRM(5,___G__23__23_append)
#define ___GLO__23__23_call_2d_with_2d_output_2d_file ___GLO(6,___G__23__23_call_2d_with_2d_output_2d_file)
#define ___PRM__23__23_call_2d_with_2d_output_2d_file ___PRM(6,___G__23__23_call_2d_with_2d_output_2d_file)
#define ___GLO_absent_2d_value ___GLO(7,___G_absent_2d_value)
#define ___PRM_absent_2d_value ___PRM(7,___G_absent_2d_value)
#define ___GLO_displayln ___GLO(8,___G_displayln)
#define ___PRM_displayln ___PRM(8,___G_displayln)
#define ___GLO_error ___GLO(9,___G_error)
#define ___PRM_error ___PRM(9,___G_error)
#define ___GLO_filter ___GLO(10,___G_filter)
#define ___PRM_filter ___PRM(10,___G_filter)
#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain ___GLO(11,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain ___PRM(11,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain)
#define ___GLO_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result ___GLO(12,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result)
#define ___PRM_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result ___PRM(12,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result)
#define ___GLO_hash_2d__3e_list ___GLO(13,___G_hash_2d__3e_list)
#define ___PRM_hash_2d__3e_list ___PRM(13,___G_hash_2d__3e_list)
#define ___GLO_hash_2d_get ___GLO(14,___G_hash_2d_get)
#define ___PRM_hash_2d_get ___PRM(14,___G_hash_2d_get)
#define ___GLO_hash_2d_put_21_ ___GLO(15,___G_hash_2d_put_21_)
#define ___PRM_hash_2d_put_21_ ___PRM(15,___G_hash_2d_put_21_)
#define ___GLO_hash_2d_ref_____25_ ___GLO(16,___G_hash_2d_ref_____25_)
#define ___PRM_hash_2d_ref_____25_ ___PRM(16,___G_hash_2d_ref_____25_)
#define ___GLO_hash_2d_remove_21_ ___GLO(17,___G_hash_2d_remove_21_)
#define ___PRM_hash_2d_remove_21_ ___PRM(17,___G_hash_2d_remove_21_)
#define ___GLO_make_2d_hash_2d_table_____25_ ___GLO(18,___G_make_2d_hash_2d_table_____25_)
#define ___PRM_make_2d_hash_2d_table_____25_ ___PRM(18,___G_make_2d_hash_2d_table_____25_)
#define ___GLO_member ___GLO(19,___G_member)
#define ___PRM_member ___PRM(19,___G_member)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0 ___GLO(20,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0 ___PRM(20,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0 ___GLO(21,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0 ___PRM(21,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0 ___GLO(22,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0 ___PRM(22,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0 ___GLO(23,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0 ___PRM(23,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0 ___GLO(24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0 ___PRM(24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
#define ___GLO_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr ___GLO(25,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr)
#define ___PRM_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr ___PRM(25,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr)
#define ___GLO_std_2f_iter_23_iter ___GLO(26,___G_std_2f_iter_23_iter)
#define ___PRM_std_2f_iter_23_iter ___PRM(26,___G_std_2f_iter_23_iter)
#define ___GLO_std_2f_iter_23_iter_2d_end ___GLO(27,___G_std_2f_iter_23_iter_2d_end)
#define ___PRM_std_2f_iter_23_iter_2d_end ___PRM(27,___G_std_2f_iter_23_iter_2d_end)
#define ___GLO_write ___GLO(28,___G_write)
#define ___PRM_write ___PRM(28,___G_write)

___DEF_SUB_BIGFIX(___X0,1UL)
               ___BIGFIX1(0x698e2c8eL)
___DEF_SUB_STR(___X1,17UL)
               ___STR8(109,105,115,115,105,110,103,32)
               ___STR8(115,101,114,118,101,114,32,105)
               ___STR1(100)
___DEF_SUB_STR(___X2,17UL)
               ___STR8(109,105,115,115,105,110,103,32)
               ___STR8(115,101,114,118,101,114,32,105)
               ___STR1(100)
___DEF_SUB_STR(___X3,17UL)
               ___STR8(109,105,115,115,105,110,103,32)
               ___STR8(115,101,114,118,101,114,32,105)
               ___STR1(100)
___DEF_SUB_STR(___X4,20UL)
               ___STR8(117,110,101,120,112,101,99,116)
               ___STR8(101,100,32,97,100,100,114,101)
               ___STR4(115,115,101,115)
___DEF_SUB_VEC(___X5,6UL)
               ___VEC1(___REF_SUB(6))
               ___VEC1(___REF_SUB(7))
               ___VEC1(___REF_NUL)
               ___VEC1(___REF_FIX(1))
               ___VEC1(___REF_PRC(1))
               ___VEC1(___REF_FAL)
               ___VEC0
___DEF_SUB_VEC(___X6,1UL)
               ___VEC1(___REF_SYM(5,___S_gerbil____tools____gxensemble____env))
               ___VEC0
___DEF_SUB_VEC(___X7,0UL)
               ___VEC0

___BEGIN_SUB
 ___DEF_SUB(___X0)
,___DEF_SUB(___X1)
,___DEF_SUB(___X2)
,___DEF_SUB(___X3)
,___DEF_SUB(___X4)
,___DEF_SUB(___X5)
,___DEF_SUB(___X6)
,___DEF_SUB(___X7)
___END_SUB



#undef ___MD_ALL
#define ___MD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___MR_ALL
#define ___MR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___MW_ALL
#define ___MW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_M_COD
___BEGIN_M_HLBL
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_gerbil____tools____gxensemble____env_23_)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L11_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L12_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L13_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L14_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L15_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L16_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L17_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L18_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L19_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L20_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L21_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L22_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L23_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L24_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L25_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L26_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L27_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L28_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L29_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L30_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L31_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L32_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L33_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L34_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L35_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L36_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L37_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L38_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L39_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L40_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L41_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L42_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L43_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L44_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L45_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L46_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L47_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L48_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L49_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L50_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L51_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L52_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L53_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L54_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L55_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L56_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L57_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L58_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L59_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L60_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L61_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L62_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL(___L63_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_M_HLBL_INTRO
___DEF_M_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_M_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___END_M_HLBL

___BEGIN_M_SW

#undef ___PH_PROC
#define ___PH_PROC ___H_gerbil____tools____gxensemble____env_23_
#undef ___PH_LBL0
#define ___PH_LBL0 1
#undef ___PD_ALL
#define ___PD_ALL ___D_R0 ___D_R1
#undef ___PR_ALL
#define ___PR_ALL ___R_R0 ___R_R1
#undef ___PW_ALL
#define ___PW_ALL ___W_R1
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_gerbil____tools____gxensemble____env_23_)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_gerbil____tools____gxensemble____env_23_)
   ___IF_NARGS_EQ(0,___NOTHING)
   ___WRONG_NARGS(0,0,0,0)
___DEF_GLBL(___L_gerbil____tools____gxensemble____env_23_)
   ___SET_GLO(3,___G_gerbil_2f_tools_2f_gxensemble_2f_env_3a__3a_timestamp,___BIGFIX(0,1770925198LL))
   ___SET_R1(___VOID)
   ___JUMPRET(___R0)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers
#undef ___PH_LBL0
#define ___PH_LBL0 3
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R3 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R3 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R3 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L11_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L12_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L13_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L14_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L15_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L16_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L17_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L18_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L19_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L20_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L21_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L22_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L23_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L24_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L25_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L26_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L27_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L28_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L29_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L30_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L31_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L32_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L33_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L34_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L35_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L36_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L37_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L38_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L39_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L40_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L41_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L42_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L43_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L44_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L45_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L46_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L47_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L48_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L49_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L50_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L51_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L52_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L53_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L54_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L55_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L56_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L57_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L58_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L59_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L60_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L61_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L62_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_P_HLBL(___L63_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R2(___SYM_add)
   ___ADJFP(8)
   ___POLL(1)
___DEF_SLBL(1,___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(2))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(2,___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L79_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_id)
   ___SET_R0(___LBL(3))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(3,___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_addresses)
   ___SET_R0(___LBL(4))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(4,___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NULLP(___R1))
   ___GOTO(___L78_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___IF(___NOTFALSEP(___STK(-5)))
   ___GOTO(___L64_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___GOTO(___L77_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(5,___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
___DEF_GLBL(___L64_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R0(___LBL(6))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_SLBL(6,___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___R1))
   ___GOTO(___L65_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(1,___FAL)
   ___SET_STK(2,___GLO_absent_2d_value)
   ___SET_STK(3,___GLO_absent_2d_value)
   ___SET_STK(4,___GLO_absent_2d_value)
   ___SET_STK(5,___GLO_absent_2d_value)
   ___SET_STK(6,___GLO_absent_2d_value)
   ___SET_R3(___GLO_absent_2d_value)
   ___SET_R2(___GLO_absent_2d_value)
   ___SET_R1(___GLO_absent_2d_value)
   ___SET_R0(___LBL(7))
   ___ADJFP(6)
   ___JUMPGLONOTSAFE(___SET_NARGS(9),18,___G_make_2d_hash_2d_table_____25_)
___DEF_SLBL(7,___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L65_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-4,___R1)
   ___SET_R2(___STK(-5))
   ___SET_R3(___NUL)
   ___SET_R0(___LBL(8))
   ___JUMPGLONOTSAFE(___SET_NARGS(3),16,___G_hash_2d_ref_____25_)
___DEF_SLBL(8,___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___BOX(___R1))
   ___CHECK_HEAP(9,4096)
___DEF_SLBL(9,___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___PAIRP(___STK(-6))))
   ___GOTO(___L76_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(-3,___R1)
   ___SET_R2(___STK(-6))
   ___SET_R0(___LBL(36))
   ___IF(___PAIRP(___R2))
   ___GOTO(___L66_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___GOTO(___L75_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(10,___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___CDR(___STK(-5)))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(11)
___DEF_SLBL(11,___L11_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___PAIRP(___R2)))
   ___GOTO(___L75_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
___DEF_GLBL(___L66_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R2(___CAR(___R2))
   ___SET_R0(___LBL(35))
   ___ADJFP(8)
   ___POLL(12)
___DEF_SLBL(12,___L12_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L67_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_R2(___UNBOX(___R1))
   ___SET_R1(___STK(3))
   ___SET_R0(___LBL(13))
   ___ADJFP(8)
   ___JUMPPRM(___SET_NARGS(2),___PRM_member)
___DEF_SLBL(13,___L13_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___R1))
   ___GOTO(___L68_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R1(___CONS(___STK(-5),___NUL))
   ___SET_R2(___R1)
   ___SET_R1(___UNBOX(___STK(-6)))
   ___SET_R0(___LBL(15))
   ___CHECK_HEAP(14,4096)
___DEF_SLBL(14,___L14_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___JUMPPRM(___SET_NARGS(2),___PRM__23__23_append)
___DEF_SLBL(15,___L15_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SETBOX(___STK(-6),___R1) ___SET_R1(___STK(-6))
   ___ADJFP(-8)
   ___JUMPRET(___STK(1))
___DEF_SLBL(16,___L16_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___EQP(___GLO_std_2f_iter_23_iter_2d_end,___R1)))
   ___GOTO(___L69_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
___DEF_GLBL(___L68_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___VOID)
   ___ADJFP(-8)
   ___JUMPRET(___STK(1))
___DEF_GLBL(___L69_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(17))
   ___GOTO(___L67_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(17,___L17_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R3(___STK(-4))
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(18)
___DEF_SLBL(18,___L18_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___GOTO(___L70_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(19,___L19_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___UNCHECKEDSTRUCTUREREF(___R1,___FIX(2L),___FAL,___FAL))
   ___SET_STK(-6,___R1)
   ___SET_R3(___R2)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-3))
   ___SET_R0(___LBL(21))
___DEF_GLBL(___L70_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_STK(3,___R2)
   ___SET_STK(4,___R3)
   ___SET_R1(___R2)
   ___ADJFP(8)
   ___POLL(20)
___DEF_SLBL(20,___L20_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(16))
   ___JUMPGENNOTSAFE(___SET_NARGS(1),___R3)
___DEF_SLBL(21,___L21_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___UNCHECKEDSTRUCTUREREF(___STK(-6),___FIX(3L),___FAL,___FAL))
   ___IF(___NOTFALSEP(___R1))
   ___GOTO(___L74_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___GOTO(___L71_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(22,___L22_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L71_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-3))
___DEF_GLBL(___L72_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R3(___UNBOX(___R1))
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-4))
   ___SET_R0(___LBL(23))
   ___JUMPGLONOTSAFE(___SET_NARGS(3),15,___G_hash_2d_put_21_)
___DEF_SLBL(23,___L23_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-4))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(24)
___DEF_SLBL(24,___L24_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___GOTO(___L73_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(25,___L25_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___ADJFP(-8)
   ___POLL(26)
___DEF_SLBL(26,___L26_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L73_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___ADJFP(8)
   ___POLL(27)
___DEF_SLBL(27,___L27_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(28))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),23,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers_2d_path____0)
___DEF_SLBL(28,___L28_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___CONS(___TRU,___NUL))
   ___SET_R2(___CONS(___KEY_truncate,___R2))
   ___SET_R2(___CONS(___SYM_maybe,___R2))
   ___SET_R2(___CONS(___KEY_create,___R2))
   ___SET_R1(___CONS(___R1,___R2))
   ___SET_R1(___CONS(___KEY_path,___R1))
   ___SET_STK(-5,___ALLOC_CLO(1UL))
   ___BEGIN_SETUP_CLO(1,___STK(-5),31)
   ___ADD_CLO_ELEM(0,___STK(-6))
   ___END_SETUP_CLO(1)
   ___SET_R2(___STK(-5))
   ___SET_R0(___STK(-7))
   ___ADJFP(-5)
   ___CHECK_HEAP(29,4096)
___DEF_SLBL(29,___L29_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___POLL(30)
___DEF_SLBL(30,___L30_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___ADJFP(-3)
   ___JUMPGLONOTSAFE(___SET_NARGS(2),6,___G__23__23_call_2d_with_2d_output_2d_file)
___DEF_SLBL(31,___L31_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(31,1,0,0)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___SET_R1(___CLO(___R4,1))
   ___ADJFP(8)
   ___POLL(32)
___DEF_SLBL(32,___L32_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(33))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),13,___G_hash_2d__3e_list)
___DEF_SLBL(33,___L33_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___STK(-6))
   ___SET_R0(___STK(-7))
   ___POLL(34)
___DEF_SLBL(34,___L34_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___ADJFP(-8)
   ___JUMPPRM(___SET_NARGS(2),___PRM_write)
___DEF_GLBL(___L74_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-2,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(22))
   ___JUMPGENNOTSAFE(___SET_NARGS(1),___STK(-2))
___DEF_SLBL(35,___L35_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___CDR(___STK(-5)))
   ___IF(___NOT(___PAIRP(___R1)))
   ___GOTO(___L68_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(-5,___R1)
   ___SET_R2(___CAR(___R1))
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(10))
   ___GOTO(___L67_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L75_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___VOID)
   ___JUMPRET(___R0)
___DEF_SLBL(36,___L36_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-3))
   ___GOTO(___L72_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L76_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NULLP(___STK(-6)))
   ___GOTO(___L72_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(-3,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(19))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),26,___G_std_2f_iter_23_iter)
___DEF_SLBL(37,___L37_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___CONS(___R1,___NUL))
   ___CHECK_HEAP(38,4096)
___DEF_SLBL(38,___L38_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___STK(-5)))
   ___GOTO(___L64_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
___DEF_GLBL(___L77_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R1(___SUB(1))
   ___SET_R0(___LBL(5))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),9,___G_error)
___DEF_GLBL(___L78_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-5))
   ___SET_R0(___LBL(37))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),25,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_server_2d_unix_2d_addr)
___DEF_GLBL(___L79_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_remove)
   ___SET_R0(___LBL(39))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(39,___L39_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L87_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_id)
   ___SET_R0(___LBL(40))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(40,___L40_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_addresses)
   ___SET_R0(___LBL(41))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(41,___L41_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___STK(-5)))
   ___GOTO(___L80_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___GOTO(___L86_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(42,___L42_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
___DEF_GLBL(___L80_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R0(___LBL(43))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_SLBL(43,___L43_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L83_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___IF(___NOT(___NOTFALSEP(___STK(-6))))
   ___GOTO(___L82_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(-6,___R1)
   ___SET_R2(___STK(-5))
   ___SET_R3(___NUL)
   ___SET_R0(___LBL(44))
   ___JUMPGLONOTSAFE(___SET_NARGS(3),16,___G_hash_2d_ref_____25_)
___DEF_SLBL(44,___L44_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-4,___ALLOC_CLO(1UL))
   ___BEGIN_SETUP_CLO(1,___STK(-4),47)
   ___ADD_CLO_ELEM(0,___R1)
   ___END_SETUP_CLO(1)
   ___SET_STK(-3,___R1)
   ___SET_R1(___STK(-4))
   ___SET_R2(___STK(-3))
   ___SET_R0(___LBL(46))
   ___CHECK_HEAP(45,4096)
___DEF_SLBL(45,___L45_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___JUMPGLOSAFE(___SET_NARGS(2),10,___G_filter)
___DEF_SLBL(46,___L46_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NULLP(___R1)))
   ___GOTO(___L81_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(25))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),17,___G_hash_2d_remove_21_)
___DEF_GLBL(___L81_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R3(___R1)
   ___SET_R2(___STK(-5))
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(25))
   ___JUMPGLONOTSAFE(___SET_NARGS(3),15,___G_hash_2d_put_21_)
___DEF_SLBL(47,___L47_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(47,1,0,0)
   ___SET_STK(1,___R0)
   ___SET_R2(___CLO(___R4,1))
   ___SET_R0(___LBL(48))
   ___ADJFP(4)
   ___JUMPPRM(___SET_NARGS(2),___PRM_member)
___DEF_SLBL(48,___L48_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___BOOLEAN(___FALSEP(___R1)))
   ___ADJFP(-4)
   ___JUMPRET(___STK(1))
___DEF_GLBL(___L82_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R2(___STK(-5))
   ___SET_R0(___LBL(25))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),17,___G_hash_2d_remove_21_)
___DEF_SLBL(49,___L49_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___R1))
   ___GOTO(___L84_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
___DEF_GLBL(___L83_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___FAL)
   ___ADJFP(-8)
   ___JUMPRET(___STK(1))
___DEF_GLBL(___L84_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___POLL(50)
___DEF_SLBL(50,___L50_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___GOTO(___L85_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(51,___L51_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R2(___R1)
   ___SET_R1(___STK(-6))
   ___SET_R0(___STK(-7))
   ___POLL(52)
___DEF_SLBL(52,___L52_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L85_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___ADJFP(-8)
   ___JUMPGLONOTSAFE(___SET_NARGS(2),12,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_write_2d_result)
___DEF_GLBL(___L86_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R1(___SUB(2))
   ___SET_R0(___LBL(42))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),9,___G_error)
___DEF_GLBL(___L87_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_set)
   ___SET_R0(___LBL(53))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(53,___L53_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L91_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_id)
   ___SET_R0(___LBL(54))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(54,___L54_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_addresses)
   ___SET_R0(___LBL(55))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(55,___L55_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___STK(-5)))
   ___GOTO(___L88_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___GOTO(___L90_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_SLBL(56,___L56_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
___DEF_GLBL(___L88_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R0(___LBL(57))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_SLBL(57,___L57_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOTFALSEP(___R1))
   ___GOTO(___L89_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(1,___FAL)
   ___SET_STK(2,___GLO_absent_2d_value)
   ___SET_STK(3,___GLO_absent_2d_value)
   ___SET_STK(4,___GLO_absent_2d_value)
   ___SET_STK(5,___GLO_absent_2d_value)
   ___SET_STK(6,___GLO_absent_2d_value)
   ___SET_R3(___GLO_absent_2d_value)
   ___SET_R2(___GLO_absent_2d_value)
   ___SET_R1(___GLO_absent_2d_value)
   ___SET_R0(___LBL(58))
   ___ADJFP(6)
   ___JUMPGLONOTSAFE(___SET_NARGS(9),18,___G_make_2d_hash_2d_table_____25_)
___DEF_SLBL(58,___L58_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
___DEF_GLBL(___L89_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-4,___R1)
   ___SET_R3(___STK(-6))
   ___SET_R2(___STK(-5))
   ___SET_R0(___LBL(23))
   ___JUMPGLONOTSAFE(___SET_NARGS(3),15,___G_hash_2d_put_21_)
___DEF_GLBL(___L90_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_STK(-6,___R1)
   ___SET_R1(___SUB(3))
   ___SET_R0(___LBL(56))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),9,___G_error)
___DEF_GLBL(___L91_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_id)
   ___SET_R0(___LBL(59))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(59,___L59_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L93_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_addresses)
   ___SET_R0(___LBL(60))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(60,___L60_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NULLP(___R1)))
   ___GOTO(___L92_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R0(___LBL(61))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_SLBL(61,___L61_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L83_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R2(___STK(-5))
   ___SET_R0(___LBL(49))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_GLBL(___L92_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R1(___SUB(4))
   ___SET_R0(___LBL(62))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),9,___G_error)
___DEF_SLBL(62,___L62_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(61))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_GLBL(___L93_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___SET_R0(___LBL(63))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),24,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_known_2d_servers____0)
___DEF_SLBL(63,___L63_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L83_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers)
   ___END_IF
   ___SET_R0(___LBL(51))
   ___JUMPGLONOTSAFE(___SET_NARGS(1),13,___G_hash_2d__3e_list)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain
#undef ___PH_LBL0
#define ___PH_LBL0 68
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___DEF_P_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___ADJFP(8)
   ___POLL(1)
___DEF_SLBL(1,___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___SET_R0(___LBL(2))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),20,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_file_2d_path____0)
___DEF_SLBL(2,___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_domain)
   ___SET_R0(___LBL(3))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(3,___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___END_IF
   ___SET_R2(___CONS(___TRU,___NUL))
   ___SET_R2(___CONS(___KEY_truncate,___R2))
   ___SET_R2(___CONS(___SYM_maybe,___R2))
   ___SET_R2(___CONS(___KEY_create,___R2))
   ___SET_R2(___CONS(___STK(-5),___R2))
   ___SET_R2(___CONS(___KEY_path,___R2))
   ___SET_STK(-6,___ALLOC_CLO(1UL))
   ___BEGIN_SETUP_CLO(1,___STK(-6),6)
   ___ADD_CLO_ELEM(0,___R1)
   ___END_SETUP_CLO(1)
   ___SET_STK(-5,___R2)
   ___SET_R2(___STK(-6))
   ___SET_R1(___STK(-5))
   ___SET_R0(___STK(-7))
   ___ADJFP(-5)
   ___CHECK_HEAP(4,4096)
___DEF_SLBL(4,___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___POLL(5)
___DEF_SLBL(5,___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___ADJFP(-3)
   ___JUMPGLONOTSAFE(___SET_NARGS(2),6,___G__23__23_call_2d_with_2d_output_2d_file)
___DEF_SLBL(6,___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(6,1,0,0)
   ___SET_R2(___R1)
   ___SET_R1(___CLO(___R4,1))
   ___POLL(7)
___DEF_SLBL(7,___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___JUMPPRM(___SET_NARGS(2),___PRM_write)
___DEF_GLBL(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___SET_R1(___STK(-6))
   ___SET_R0(___LBL(8))
   ___ADJFP(-4)
   ___JUMPGLONOTSAFE(___SET_NARGS(1),11,___G_gerbil_2f_tools_2f_gxensemble_2f_util_23_get_2d_ensemble_2d_domain)
___DEF_SLBL(8,___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___SET_R0(___STK(-3))
   ___POLL(9)
___DEF_SLBL(9,___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain)
   ___ADJFP(-4)
   ___JUMPGLONOTSAFE(___SET_NARGS(1),8,___G_displayln)
___END_P_SW
___END_P_COD

#undef ___PH_PROC
#define ___PH_PROC ___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor
#undef ___PH_LBL0
#define ___PH_LBL0 79
#undef ___PD_ALL
#define ___PD_ALL ___D_HEAP ___D_FP ___D_R0 ___D_R1 ___D_R2 ___D_R4
#undef ___PR_ALL
#define ___PR_ALL ___R_HEAP ___R_FP ___R_R0 ___R_R1 ___R_R2 ___R_R4
#undef ___PW_ALL
#define ___PW_ALL ___W_HEAP ___W_FP ___W_R0 ___W_R1 ___W_R2 ___W_R4
___BEGIN_P_COD
___BEGIN_P_HLBL
___DEF_P_HLBL_INTRO
___DEF_P_HLBL(___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___DEF_P_HLBL(___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
___END_P_HLBL
___BEGIN_P_SW
___DEF_SLBL(0,___L0_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(0,1,0,0)
___DEF_GLBL(___L_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___SET_STK(1,___R0)
   ___SET_STK(2,___R1)
   ___ADJFP(8)
   ___POLL(1)
___DEF_SLBL(1,___L1_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___SET_R0(___LBL(2))
   ___JUMPGLONOTSAFE(___SET_NARGS(0),21,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor_2d_path____0)
___DEF_SLBL(2,___L2_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___SET_STK(-5,___R1)
   ___SET_R1(___STK(-6))
   ___SET_R2(___SYM_server_2d_id)
   ___SET_R0(___LBL(3))
   ___JUMPGLONOTSAFE(___SET_NARGS(2),14,___G_hash_2d_get)
___DEF_SLBL(3,___L3_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___IF(___NOT(___NOTFALSEP(___R1)))
   ___GOTO(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___END_IF
   ___SET_R2(___CONS(___TRU,___NUL))
   ___SET_R2(___CONS(___KEY_truncate,___R2))
   ___SET_R2(___CONS(___SYM_maybe,___R2))
   ___SET_R2(___CONS(___KEY_create,___R2))
   ___SET_R2(___CONS(___STK(-5),___R2))
   ___SET_R2(___CONS(___KEY_path,___R2))
   ___SET_STK(-6,___ALLOC_CLO(1UL))
   ___BEGIN_SETUP_CLO(1,___STK(-6),6)
   ___ADD_CLO_ELEM(0,___R1)
   ___END_SETUP_CLO(1)
   ___SET_STK(-5,___R2)
   ___SET_R2(___STK(-6))
   ___SET_R1(___STK(-5))
   ___SET_R0(___STK(-7))
   ___ADJFP(-5)
   ___CHECK_HEAP(4,4096)
___DEF_SLBL(4,___L4_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___POLL(5)
___DEF_SLBL(5,___L5_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___ADJFP(-3)
   ___JUMPGLONOTSAFE(___SET_NARGS(2),6,___G__23__23_call_2d_with_2d_output_2d_file)
___DEF_SLBL(6,___L6_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___IF_NARGS_EQ(1,___NOTHING)
   ___WRONG_NARGS(6,1,0,0)
   ___SET_R2(___R1)
   ___SET_R1(___CLO(___R4,1))
   ___POLL(7)
___DEF_SLBL(7,___L7_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___JUMPPRM(___SET_NARGS(2),___PRM_write)
___DEF_GLBL(___L10_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___SET_R0(___LBL(8))
   ___ADJFP(-4)
   ___JUMPGLONOTSAFE(___SET_NARGS(0),22,___G_std_2f_actor_2d_v18_2f_path_23_ensemble_2d_domain_2d_supervisor____0)
___DEF_SLBL(8,___L8_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___SET_R0(___STK(-3))
   ___POLL(9)
___DEF_SLBL(9,___L9_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor)
   ___ADJFP(-4)
   ___JUMPGLONOTSAFE(___SET_NARGS(1),8,___G_displayln)
___END_P_SW
___END_P_COD

___END_M_SW
___END_M_COD

___BEGIN_LBL
 ___DEF_LBL_INTRO(___H_gerbil____tools____gxensemble____env_23_,___REF_SYM(6,___S_gerbil____tools____gxensemble____env_23_),___REF_FAL,1,0)
,___DEF_LBL_PROC(___H_gerbil____tools____gxensemble____env_23_,0,-1)
,___DEF_LBL_INTRO(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___REF_SYM(3,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers),___REF_FAL,64,0)
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,1,-1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x5L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0xfL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x1dL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f0fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x1fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x1dL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x9L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,1,1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x1dL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x5L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f05L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x5L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,0,0x3f07L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,1,1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETI,8,8,0x3f00L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x5L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_INTRO(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___REF_SYM(2,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain),___REF_FAL,10,0)
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,1,-1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETN,5,0,0x7L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,1,1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,___IFD(___RETI,4,4,0x3f0L))
,___DEF_LBL_INTRO(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___REF_SYM(4,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor),___REF_FAL,10,0)
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,1,-1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETI,8,0,0x3f03L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETN,5,0,0x3L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETN,5,0,0x5L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETI,3,4,0x3f0L))
,___DEF_LBL_PROC(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,1,1)
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETI,0,0,0x3fL))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETN,1,0,0x1L))
,___DEF_LBL_RET(___H_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,___IFD(___RETI,4,4,0x3f0L))
___END_LBL

___BEGIN_MOD_PRM
___DEF_MOD_PRM(4,___G_gerbil____tools____gxensemble____env_23_,1)
___DEF_MOD_PRM(1,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,3)
___DEF_MOD_PRM(0,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,68)
___DEF_MOD_PRM(2,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,79)
___END_MOD_PRM

___BEGIN_MOD_C_INIT
___END_MOD_C_INIT

___BEGIN_MOD_GLO
___DEF_MOD_GLO(4,___G_gerbil____tools____gxensemble____env_23_,1)
___DEF_MOD_GLO(1,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,3)
___DEF_MOD_GLO(0,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,68)
___DEF_MOD_GLO(2,___G_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,79)
___END_MOD_GLO

___BEGIN_MOD_SYM_KEY
___DEF_MOD_SYM(0,___S_add,"add")
___DEF_MOD_SYM(1,___S_domain,"domain")
___DEF_MOD_SYM(2,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_domain,"gerbil/tools/gxensemble/env#do-env-domain")

___DEF_MOD_SYM(3,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_known_2d_servers,"gerbil/tools/gxensemble/env#do-env-known-servers")

___DEF_MOD_SYM(4,___S_gerbil_2f_tools_2f_gxensemble_2f_env_23_do_2d_env_2d_supervisor,"gerbil/tools/gxensemble/env#do-env-supervisor")

___DEF_MOD_SYM(5,___S_gerbil____tools____gxensemble____env,"gerbil__tools__gxensemble__env")

___DEF_MOD_SYM(6,___S_gerbil____tools____gxensemble____env_23_,"gerbil__tools__gxensemble__env#")

___DEF_MOD_SYM(7,___S_maybe,"maybe")
___DEF_MOD_SYM(8,___S_remove,"remove")
___DEF_MOD_SYM(9,___S_server_2d_addresses,"server-addresses")
___DEF_MOD_SYM(10,___S_server_2d_id,"server-id")
___DEF_MOD_SYM(11,___S_set,"set")
___DEF_MOD_KEY(0,___K_create,"create")
___DEF_MOD_KEY(1,___K_path,"path")
___DEF_MOD_KEY(2,___K_truncate,"truncate")
___END_MOD_SYM_KEY

#endif
